from enum import IntEnum


class DeviceModeEnum(IntEnum):
    """Device operating modes"""
    HEAT_RECOVERY = 1
    EXTRACTION = 2
    IMMISSION = 3
    HUMIDITY_RECOVERY = 4
    HUMIDITY_EXTRACTION = 5
    COMFORT_SUMMER = 6
    COMFORT_WINTER = 7
    CO2_RECOVERY = 8
    CO2_EXTRACTION = 9
    HUMIDITY_CO2_RECOVERY = 10
    HUMIDITY_CO2_EXTRACTION = 11
    NATURAL_VENTILATION = 12